### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by vr2262** [ambv/flake8-mypy#34]
There hasn't been any activity on this repo in quite some time. Is there a new recommended way to integrate `mypy` with `flake8`?

**Comment by maxcountryman** [comment]
Also wondering what the preferred way of integration `mypy` with `flake8` is.

**Comment by ssbarnea** [comment]
I suppose we can call it dead as in this area even one year w/o a release is making a project not practical for use.

**Comment by hjmjohnson** [comment]
Ran into a bug but it seems this is a dead project not worth submitting a PR to.

```
import regex as re
```
```
line 293
MYPY_ERROR_TEMPLATE.format(filename=re_filename).encode('unicode-escape').decode(),
```

**Comment by ambv** [comment]
Yeah, the project is pretty much dead, sorry. Integrating Flake8 with Mypy was a workaround for Mypy's insufficient performance at the time. flake8-mypy traded performance for capability: Mypy could only find problems within the file + against the standard library.

These days Mypy is both much faster due to mypyc, as well as good aggressive caching. There's no need to trade performance for correctness anymore.
